apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tk-pipelines.name" }}-role-binding
  labels:
    app.kubernetes.io/name: {{ include "tk-pipelines.name" . }}
    helm.sh/chart: {{ include "tk-pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tk-pipelines.name" }}
    namespace: {{ Release.Namspace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io