apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tk-pipelines.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "tk-pipelines.name" . }}
    helm.sh/chart: {{ include "tk-pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tk-pipelines.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "tk-pipelines.name" . }}
    helm.sh/chart: {{ include "tk-pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/service-account.name: {{ include "tk-pipelines.name" . }}
type: kubernetes.io/service-account-token