apiVersion: tekton.dev/vbeta1
kind: Pipeline
metadata:
  name: helm-uninstall-pipeline
  labels:
    app.kubernetes.io/name: {{ include "tk-pipelines.name" . }}
    helm.sh/chart: {{ include "tk-pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  params:
    - name: cluster_config
      description: The cluster kube configuration to use
      default: ""
    - name: name
      description: The helm release name
    - name: namespace
      description: The namespace to execute against
      default: "default"
  tasks:
    - name: helm-uninstall-package
      params:
        - name: cluster_config
          value: $(params.cluster_config)
        - name: name
          value: $(params.name)
        - name: namespace
          value: $(params.namespace)
      taskRef:
        name: helm-uninstall