apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helm-uninstall-all
  labels:
    app.kubernetes.io/name: {{ include "tk-pipelines.name" . }}
    helm.sh/chart: {{ include "tk-pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  description: >-
    Uninstall all helm packages

  params:
    - name: cluster_config
      description: The cluster kube configuration to use
      default: ""
    - name: namespace
      description: The namespace to execute against
      default: "default"
    - name: image
      description: Container image to be used
      default: "alpine/helm:3.10.2"
  steps:
    - name: uninstall-all
      image: $(params.image)
      script: |

        if [[ -z "$(params.cluster_config)" ]]; then
            echo Uninstalling chart from default cluster ...
            helm delete --namespace "$(params.namespace)" $(helm ls --short --namespace "$(params.namespace)")
        else
            echo Uninstalling chart from external cluster ...
            echo "$(params.cluster_config)" > config
            helm delete --namespace "$(params.namespace)" --kubeconfig config $(helm ls --short --namespace "$(params.namespace)")
        fi


