apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-tls-certificate
  labels:
    app.kubernetes.io/name: {{ include "tk-pipelines.name" . }}
    helm.sh/chart: {{ include "tk-pipelines.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  description: >-
    Creates a tls certificate manually

  params:
    - name: cluster_config
      description: The cluster kube configuration to use
      default: ""
    - name: name
      description: The name of the tls secret
      default: "default-tls-cert"
    - name: namespace
      description: The namespace to execute against
      default: "default"
    - name: cert
      description: The certificate pem file
      default: ""
    - name: key
      description: The certificate key file
      default: ""
    - name: image
      description: Container image to be used
      default: "bitnami/kubectl:1.25.5"
  steps:
    - name: create-tls-certificate
      image: $(params.image)
      script: |
        kubectl version

        echo Creating cert pem file
        echo
        echo "$(params.cert)" > /tmp/cert.crt

        echo Creating key file
        echo
        echo "$(params.key)" > /tmp/cert.key

        if [[ -z "$(params.cluster_config)" ]]; then
            echo creating certificate to default cluster ...
            kubectl create secret tls "$(params.name)" --cert=/tmp/cert.crt --key=/tmp/cert.key --namespace "$(params.namespace)" --dry-run=client -o yaml | kubectl apply -f -
        else
            echo creating certificate to external cluster ...
            echo "$(params.cluster_config)" > /tmp/config
            kubectl create secret tls "$(params.name)" --cert=/tmp/cert.crt --key=/tmp/cert.key --namespace "$(params.namespace)" --dry-run=client -o yaml | kubectl apply --kubeconfig /tmp/config -f -
        fi


